## Biblioteki

In [90]:
import numpy as np
import pandas as pd

## Tworzenie Macierzy

In [91]:
#Tworzenie macierzy jedno i dwu wymiarowych
lista_1 = [50,60,80,10,200,300,500,600]
macierz_numpy = np.array(lista_1) #macierz jednowymiarowa z lista_1
macierz_numpy_2 = np.array(([2,5,8] , [7,3,6])) #macierz dwuwymiarowa
macierz_numpy_3 = np.array(([6,7,1],[9,5,8],[8,1,6])) #macierz trójwymiarowa

## Metody w numpy

In [92]:
x = np.random.rand(4,4) #Tworzenie losowej macierzy 4 x 4
x

array([[0.04476961, 0.91678942, 0.25423115, 0.3934638 ],
       [0.86315531, 0.46039569, 0.50396576, 0.38870597],
       [0.73444967, 0.70917573, 0.07976033, 0.8132057 ],
       [0.29764844, 0.60297999, 0.85725623, 0.26125409]])

In [93]:
x = np.random.randint(1,50) #Losowa liczba pomiędzy 1 a 50
x

32

In [94]:
x = np.random.randint(1,100,15) #Macierz jednowymiarowa losowych numerów pomiędzy 1 a 100
x

array([63, 33, 90, 73, 19, 32, 31, 85,  9, 40, 82, 64, 30, 26, 38])

In [95]:
x = np.arange(1,31) #Macierz jednowymiarowa liczb od 1 do 30
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [96]:
x = np.eye(7) #Macierz diagonalna 7 x 7
x

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [97]:
x = np.ones((6,6)) #Macierz samych liczb 1 6 x 6 
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [98]:
x = np.zeros(8) #Macierz jednowymiarowa 8 zer
x

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [99]:
#Macierz jednowymiarowa 10 elementów przechowujące elementy od 1 do wprowadzonego x 
x = int(input('Wprowadź wartość do której mają być losowane elementy w tablicy'))
x = np.random.randint(1,x,10)
x

array([ 9, 21,  9,  1, 12, 19, 48, 49, 48, 35])

## Operacje matematyczne w numpy

In [100]:
#Dodawanie macierzy jednowymiarowych
x = np.arange(1,10)
y = np.arange(1,10)
suma = x + y
suma

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [101]:
#Potęgowanie macierzy jednowymiarowej x
potega = x ** 2
potega

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [102]:
#Pierwiastek z macierzy potęga
pierwiastek = np.sqrt(potega)
pierwiastek

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [103]:
#Funkcja wykładnicza o podstawie e z y 
z = np.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [104]:
#Odległość pomiędzy x a y
x = np.array([5,7,20])
y = np.array([9,15,4])
z = np.sqrt( x ** 2 + y ** 2)
z

array([10.29563014, 16.55294536, 20.39607805])

## Operacje na macierzach

In [105]:
macierz_numpy = np.array([3,5,6,2,8,10,20,50])
macierz_numpy[0] + macierz_numpy[-1] #Pierwszy element macierzy + ostatni elemement macierzy


53

In [106]:
macierz_numpy[0:3] #Elementy od 0 do 3 

array([3, 5, 6])

In [107]:
#Zamiana pierwszych 4 elementów na 7
macierz_numpy[0:4] = 7 
macierz_numpy

array([ 7,  7,  7,  7,  8, 10, 20, 50])

In [108]:
macierz = np.random.randint(1,10,(4,4)) #Macierz dwuwymiarowa 4 x 4 elementów od 1 do 10
macierz[0][3] #Wartość o kolumnie 1 i rzędzie 3 

1

In [109]:
macierz = ([[2,30,20,-2,4],
             [3,4,40,-3,-2],
             [-3,4,-6,90,10],
             [25,45,34,22,12],
             [13,24,22,32,37]])
macierz[-1] = 0 #Wyzerowanie ostatniego rzędu macierzy 

In [110]:
#Wybranie tylko elementów większych niż 5 z macierzy 5 x 5 losowych liczb od 1 do 10
macierz = np.random.randint(1,10,(5,5))
macierz_wiekszaniz2 = macierz[macierz > 5]
macierz_wiekszaniz2 


array([9, 9, 7, 8, 9, 8, 7, 6, 8, 8, 8, 8, 9, 6])

In [111]:
#Wybranie tylko elementów parzystych macierzy 5 x 5 losowych liczb od 1 do 10
macierz_parzyste = macierz[macierz % 2 == 0]
macierz_parzyste

array([2, 4, 2, 8, 8, 4, 6, 4, 2, 4, 8, 8, 8, 8, 6])

## Podstawy pandas

In [112]:
#Przykładowa baza danych

klient_banku_df = pd.DataFrame({'Id Klienta':[111,222,333,444],
                                 'Imie Klienta':['Maciej','Katarzyna','Marcin','Stefan'],
                                 'Zarobki [zł]':[2000,3000,5000,3500],
                                 'Lata z Bankiem':[4,2,7,8]})
klient_banku_df

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
1         222    Katarzyna          3000               2
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [113]:
#Typ danych klient_banku_df
type(klient_banku_df)

pandas.core.frame.DataFrame

In [114]:
#Pierwsze 2 rzędy 
klient_banku_df.head(2)

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
1         222    Katarzyna          3000               2

In [115]:
#Ostatnie 2 rzędy
klient_banku_df.tail(2)

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [116]:
#Przykładowa baza danych
portfolio_df = pd.DataFrame({'Symbol giełdowy':['AAPL','AMZN','T'],
                            'Cena':[3500,200,40],
                            'Ilosc':[3,4,9]})
portfolio_df

Symbol giełdowy  Cena  Ilosc
0            AAPL  3500      3
1            AMZN   200      4
2               T    40      9

In [117]:
#Zliczenie ceny akcji
cena_akcji = portfolio_df['Cena']* portfolio_df['Ilosc']
cena_akcji

0    10500
1      800
2      360
dtype: int64

In [118]:
#Sumowanie cen akcji
cena_akcji.sum()

11660

## Zczytywanie danych z użyciem pandas ze stron internetowych

In [119]:
#Zczytanie danych ze strony livingin-canada
ceny_domow_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
ceny_domow_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [120]:
ceny_domow_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

In [121]:
#Zczytanie danych emerytury w stanach
emerytura_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
emerytura_df[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# Operacje na danych z użyciem pandas

In [122]:
#Użycie poprzedniej bazy danych
klient_banku_df = pd.DataFrame({'Id Klienta':[111,222,333,444],
                                 'Imie Klienta':['Maciej','Katarzyna','Marcin','Stefan'],
                                 'Zarobki [zł]':[2000,3000,5000,3500],
                                 'Lata z Bankiem':[4,2,7,8]})
klient_banku_df

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
1         222    Katarzyna          3000               2
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [123]:
#Wyświetlenie osób które mają 4 lub więcej lata z bankiem
df_CzasZBankiem = klient_banku_df[klient_banku_df['Lata z Bankiem'] >= 4]
df_CzasZBankiem

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [124]:
#Usunięcie kolumny z Id
del klient_banku_df['Id Klienta']
klient_banku_df

Imie Klienta  Zarobki [zł]  Lata z Bankiem
0       Maciej          2000               4
1    Katarzyna          3000               2
2       Marcin          5000               7
3       Stefan          3500               8

In [125]:
#Wyświetlenie osób z zarobkami powyżej 3000 zł
df_kliencipowyzej3k = klient_banku_df[klient_banku_df['Zarobki [zł]'] > 3000]
df_kliencipowyzej3k

Imie Klienta  Zarobki [zł]  Lata z Bankiem
2       Marcin          5000               7
3       Stefan          3500               8

In [126]:
#Suma zarobków klientów zarabiających powyżej 3000 zł
df_kliencipowyzej3k['Zarobki [zł]'].sum()

8500

# Funkcje w pandas

In [127]:
#Użycie poprzedniej bazy danych
klient_banku_df = pd.DataFrame({'Id Klienta':[111,222,333,444],
                                 'Imie Klienta':['Maciej','Katarzyna','Marcin','Stefan'],
                                 'Zarobki [zł]':[2000,3000,5000,3500],
                                 'Lata z Bankiem':[4,2,7,8]})
klient_banku_df

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
1         222    Katarzyna          3000               2
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [128]:
#Funkcja która zwiększa zarobki klientów o 30%

def zarobki(zarobki):
    return zarobki * 1.3

In [129]:
klient_banku_df['Zarobki [zł]'].apply(zarobki)

0    2600.0
1    3900.0
2    6500.0
3    4550.0
Name: Zarobki [zł], dtype: float64

In [130]:
#Funkcja podwajająca cenę akcji i dodająca 100 

def akcje(akcja):
    return akcja * 2 + 100

In [131]:
#Użycie poprzedniej bazy danych
portfolio_df = pd.DataFrame({'Symbol giełdowy':['AAPL','AMZN','T'],
                            'Cena':[3500,200,40],
                            'Ilosc':[3,4,9]})
portfolio_df

Symbol giełdowy  Cena  Ilosc
0            AAPL  3500      3
1            AMZN   200      4
2               T    40      9

In [132]:
portfolio_df['Cena'].apply(akcje)

0    7100
1     500
2     180
Name: Cena, dtype: int64

# Sortowanie w pandas

In [133]:
#Użycie poprzedniej bazy danych
klient_banku_df = pd.DataFrame({'Id Klienta':[111,222,333,444],
                                 'Imie Klienta':['Maciej','Katarzyna','Marcin','Stefan'],
                                 'Zarobki [zł]':[2000,3000,5000,3500],
                                 'Lata z Bankiem':[4,2,7,8]})
klient_banku_df

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
0         111       Maciej          2000               4
1         222    Katarzyna          3000               2
2         333       Marcin          5000               7
3         444       Stefan          3500               8

In [134]:
#Sortowanie przez lata z bankiem i zastosowanie tego

klient_banku_df.sort_values(by = 'Lata z Bankiem', inplace = True)
klient_banku_df

Id Klienta Imie Klienta  Zarobki [zł]  Lata z Bankiem
1         222    Katarzyna          3000               2
0         111       Maciej          2000               4
2         333       Marcin          5000               7
3         444       Stefan          3500               8

# Łączenie w pandas

In [135]:
#Przykładowa baza danych
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3'],},
                    index = [0,1,2,3])
df1

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [136]:
#Przykładowa baza danych
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7'],},
                    index = [4,5,6,7])
df2

A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [137]:
#Łączenie 2 baz
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

# Użycie wszystkich infomracji

In [138]:
#Utworzenie bazy 1
Bank_df_1 = pd.DataFrame({'Id_Klienta':[1,2,3,4,5],
                          'Imie':['Stefan','Melania','Katarzyna','Marcin','Maciej'],
                          'Nazwisko':['Kowalski','Nowak','Pokrzywiak','Nowak','Kowal']})
#Utworzenie bazy 2
Bank_df_2 = pd.DataFrame({'Id_Klienta':[6,7,8,9,10],
                          'Imie':['Stefan1','Melania2','Katarzyna3','Marcin4','Maciej5'],
                          'Nazwisko':['Kowalski1','Nowak2','Pokrzywiak3','Nowak4','Kowal5']})
#Dane bez struktury
Zarobki = ({'Id_Klienta':[1,2,3,4,5,6,7,8,9,10],
                        'Zarobki':[4000,6300,7400,3400,6400,7400,8500,1500,6400,6300]})
Zarobki_df = pd.DataFrame(Zarobki, columns= ['Id_Klienta','Zarobki'])

#Łączenie informacji z bazy 1 i 2
Bank_df_3 = pd.concat([Bank_df_1,Bank_df_2])

#Połączenie bazy Zarobki po Id_Klienta
Bank_df_4 = pd.merge(Bank_df_3, Zarobki_df, on = 'Id_Klienta')

#Dodanie nowego klienta
nowy_klient = {'Id_Klienta':['11'],
               'Imie':['Adam'],
               'Nazwisko':['Wójcik'],
               'Zarobki':['6100']}

nowy_klient_df = pd.DataFrame(nowy_klient, columns=['Id_Klienta','Imie','Nazwisko','Zarobki'])

Bank_df = pd.concat([Bank_df_4, nowy_klient_df], axis = 0)
Bank_df

Id_Klienta        Imie     Nazwisko Zarobki
0          1      Stefan     Kowalski    4000
1          2     Melania        Nowak    6300
2          3   Katarzyna   Pokrzywiak    7400
3          4      Marcin        Nowak    3400
4          5      Maciej        Kowal    6400
5          6     Stefan1    Kowalski1    7400
6          7    Melania2       Nowak2    8500
7          8  Katarzyna3  Pokrzywiak3    1500
8          9     Marcin4       Nowak4    6400
9         10     Maciej5       Kowal5    6300
0         11        Adam       Wójcik    6100